name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on pushing to the 'main' branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '16.x'  # Specify the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install  # Install dependencies from package.json

      # Build the React app
      - name: Build React app
        run: |
          npm run build  # Builds the React app using Vite

      # Deploy to GitHub Pages
      - name: Deploy React App to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to (should be 'gh-pages')
          folder: dist  # The build output folder for Vite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
